// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MySQLServiceInterface is an autogenerated mock type for the MySQLServiceInterface type
type MySQLServiceInterface struct {
	mock.Mock
}
