// Code generated by mockery v2.35.3. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

type Handler_Expecter struct {
	mock *mock.Mock
}

func (_m *Handler) EXPECT() *Handler_Expecter {
	return &Handler_Expecter{mock: &_m.Mock}
}

// Health provides a mock function with given fields: c
func (_m *Handler) Health(c *gin.Context) {
	_m.Called(c)
}

// Handler_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type Handler_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - c *gin.Context
func (_e *Handler_Expecter) Health(c interface{}) *Handler_Health_Call {
	return &Handler_Health_Call{Call: _e.mock.On("Health", c)}
}

func (_c *Handler_Health_Call) Run(run func(c *gin.Context)) *Handler_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *Handler_Health_Call) Return() *Handler_Health_Call {
	_c.Call.Return()
	return _c
}

func (_c *Handler_Health_Call) RunAndReturn(run func(*gin.Context)) *Handler_Health_Call {
	_c.Call.Return(run)
	return _c
}

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandler(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Handler {
	mock := &Handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
