// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	so "cabother-go-helpers/pkg/so"

	mock "github.com/stretchr/testify/mock"
)

// EnvironmentInterface is an autogenerated mock type for the EnvironmentInterface type
type EnvironmentInterface struct {
	mock.Mock
}

// GetEnvironmentConfigs provides a mock function with given fields:
func (_m *EnvironmentInterface) GetEnvironmentConfigs() *so.EnvironmentConfig {
	ret := _m.Called()

	var r0 *so.EnvironmentConfig
	if rf, ok := ret.Get(0).(func() *so.EnvironmentConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*so.EnvironmentConfig)
		}
	}

	return r0
}
